#proxyServer: "localhost"
server: "http://localhost:8080"
token: "bdc66030-a1a8-493b-b416-5559fdcfa45d"
#server: "https://durian.wavefront.com"
#token: "c6ba002e-3c5e-413b-9d41-63167aa5b164"
## uncomment for generating traces to file
## this option has the highest priority and will block trace ingestion to Wavefront
#outputFile: "traces.txt"